server {
    listen 80;
    root /var/www/public;
    index index.php index.html;
    client_max_body_size 100M;

    location /promo-concierto/backoffice/ {
        rewrite ^/promo-concierto/backoffice/(.*)$ /$1 last;
    }

    # Proxy a Vite dev server
    location ~ ^/@(vite|react-refresh|fs) {
        proxy_pass http://campanias_node:5173;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
    }

    location /resources/ {
        proxy_pass http://campanias_node:5173;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
    }

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass campanias_app:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }
}